name: Android CI

on: [push]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: "1.8"
      - name: gradle
        run: chmod +x ./gradlew
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: default
          script: ./gradlew check && ./gradlew connectedCheck
